---
- name : "Installing Node Exporter"
  hosts: targets
  become: true
  vars:
    URL: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    ex_version: 1.3.1
    arch: amd64
  tasks:
    - include_tasks: node_exporter.yml
